#
# # 03 · Intelligence — winter overload risk (ML) & protection-zone risk (AI Functions)
#
# 1. **Transformer thermal-overload model** — gradient-boosted classifier predicting whether a transformer
#    will exceed **150 %** of nameplate during the *next* winter peak.
#    *Train*: features from **Hiver 2025** (Dec 2024 → Mar 2025) → label = overload > 150 % in **Hiver 2026**.
#    *Score*: features from **Hiver 2026** → risk for the coming **Hiver 2027** (Dec 2026 → Mar 2027).
#    Tracked in MLflow, registered in Unity Catalog (`grid_genie.gold.transformer_overload_model`).
# 2. **Protection-zone risk classification** — CHI trend × asset age × predicted overloads → risk tier,
#    with a bilingual dispatcher recommendation generated by `ai_query` for the highest-risk zones.
# 3. **Operational tables** (`gold.ops_*`, scalar columns only) consumed by Lakebase.

# ---------------------------------------------------------------------------------------------

import sys

import mlflow
import numpy as np
import pandas as pd
from mlflow.models import infer_signature
from pyspark.sql import SparkSession
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import average_precision_score, roc_auc_score
from sklearn.model_selection import train_test_split

spark = SparkSession.builder.getOrCreate()


def _arg(name, default):
    if f"--{name}" in sys.argv:
        return sys.argv[sys.argv.index(f"--{name}") + 1]
    return default


CATALOG = _arg("catalog", "grid_genie")
LLM_ENDPOINT = _arg("llm_endpoint", "databricks-claude-sonnet-4-6")
GOLD = f"{CATALOG}.gold"
MODEL_NAME = f"{GOLD}.transformer_overload_model"

# ---------------------------------------------------------------------------------------------

### 1 · Feature engineering (one row per transformer × winter)

# ---------------------------------------------------------------------------------------------

FEATURES = ["max_overload_pct", "p95_overload_pct", "days_over_120", "days_over_150",
            "kva_per_degree_below_15", "kva", "age_years", "n_customers", "electric_heating_share",
            "customers_per_10kva", "is_urban"]


def winter_features(winter_label: str) -> pd.DataFrame:
    return spark.sql(f"""
        WITH w AS (
          SELECT transformer_id,
                 max(overload_pct)                         AS max_overload_pct,
                 percentile_approx(overload_pct, 0.95)     AS p95_overload_pct,
                 count_if(overload_pct > 120)              AS days_over_120,
                 count_if(overload_pct > 150)              AS days_over_150,
                 -- load sensitivity to cold: regression slope of peak kVA on degrees below 15 °C
                 regr_slope(peak_kva, greatest(0, 15 - temp_min_c)) AS kva_per_degree_below_15
          FROM {GOLD}.transformer_load_daily
          WHERE winter_label = '{winter_label}'
          GROUP BY transformer_id)
        SELECT t.transformer_id, t.line_id, t.ced_code, t.kva, t.age_years, t.n_customers,
               coalesce(t.electric_heating_share, 0) AS electric_heating_share,
               10 * t.n_customers / t.kva AS customers_per_10kva,
               CAST(o.is_urban AS INT) AS is_urban, w.* EXCEPT (transformer_id)
        FROM {GOLD}.transformers t
        JOIN {GOLD}.operating_centers o USING (ced_code)
        JOIN w USING (transformer_id)""").toPandas()


train_x = winter_features("Hiver 2025")
label = spark.sql(f"""
    SELECT transformer_id, CAST(max(overload_pct) > 150 AS INT) AS overload_next_winter
    FROM {GOLD}.transformer_load_daily WHERE winter_label = 'Hiver 2026' GROUP BY transformer_id""").toPandas()
train = train_x.merge(label, on="transformer_id")
train[FEATURES] = train[FEATURES].astype(float)
print(f"training rows={len(train)}, positive rate={train.overload_next_winter.mean():.3f}")

# ---------------------------------------------------------------------------------------------

### 2 · Train, evaluate and register the model

# ---------------------------------------------------------------------------------------------

mlflow.set_registry_uri("databricks-uc")
user = spark.sql("SELECT current_user()").first()[0]
mlflow.set_experiment(f"/Users/{user}/grid_genie_transformer_overload")

X_tr, X_te, y_tr, y_te = train_test_split(train[FEATURES], train.overload_next_winter,
                                          test_size=0.25, random_state=42, stratify=train.overload_next_winter)

with mlflow.start_run(run_name="hgb_overload_hiver2026") as run:
    params = {"max_iter": 300, "learning_rate": 0.05, "max_depth": 4, "l2_regularization": 1.0,
              "class_weight": "balanced", "random_state": 42}
    model = HistGradientBoostingClassifier(**params).fit(X_tr, y_tr)
    p_te = model.predict_proba(X_te)[:, 1]
    metrics = {"roc_auc": roc_auc_score(y_te, p_te), "pr_auc": average_precision_score(y_te, p_te),
               "positive_rate": float(y_te.mean())}
    # Naive baseline: "it overloaded last winter, it will overload next winter"
    metrics["baseline_last_winter_recall"] = float(((X_te.max_overload_pct > 150) & (y_te == 1)).sum() / max(1, y_te.sum()))
    metrics["model_recall_at_0_5"] = float(((p_te >= 0.5) & (y_te == 1)).sum() / max(1, y_te.sum()))
    mlflow.log_params(params)
    mlflow.log_metrics(metrics)
    model = HistGradientBoostingClassifier(**params).fit(train[FEATURES], train.overload_next_winter)
    log_kwargs = dict(name="model", registered_model_name=MODEL_NAME,
                      signature=infer_signature(train[FEATURES], model.predict_proba(train[FEATURES])[:, 1]),
                      input_example=train[FEATURES].head(5))
    try:  # MLflow ≥ 3.x serialises sklearn with skops: declare the one type this self-trained model needs
        mlflow.sklearn.log_model(model, skops_trusted_types=[
            "sklearn.ensemble._hist_gradient_boosting.predictor.TreePredictor"], **log_kwargs)
    except TypeError:  # older MLflow without skops support
        mlflow.sklearn.log_model(model, **log_kwargs)
    print(metrics)

client = mlflow.MlflowClient()
latest = max(int(v.version) for v in client.search_model_versions(f"name = '{MODEL_NAME}'"))
client.set_registered_model_alias(MODEL_NAME, "champion", latest)

# ---------------------------------------------------------------------------------------------

### 3 · Score the coming winter (Hiver 2027) and persist predictions

# ---------------------------------------------------------------------------------------------

score_x = winter_features("Hiver 2026")
score_x[FEATURES] = score_x[FEATURES].astype(float)
score_x["risk_score"] = model.predict_proba(score_x[FEATURES])[:, 1]
score_x["risk_tier"] = pd.cut(score_x.risk_score, [-0.01, 0.3, 0.6, 1.01], labels=["FAIBLE", "MOYEN", "ÉLEVÉ"]).astype(str)
score_x["target_winter"] = "Hiver 2027"
score_x["model_version"] = latest

(spark.createDataFrame(score_x[["transformer_id", "line_id", "ced_code", "target_winter", "risk_score", "risk_tier",
                                "max_overload_pct", "days_over_150", "kva", "n_customers", "model_version"]]
                       .rename(columns={"max_overload_pct": "max_overload_pct_last_winter",
                                        "days_over_150": "days_over_150_last_winter"}))
 .write.mode("overwrite").option("overwriteSchema", "true").saveAsTable(f"{GOLD}.transformer_risk"))

spark.sql(f"""COMMENT ON TABLE {GOLD}.transformer_risk IS
  'Risque de surcharge thermique / predicted probability that the transformer exceeds 150 % of nameplate during Hiver 2027 (Dec 2026 → Mar 2027). risk_tier: FAIBLE < 0.3 ≤ MOYEN < 0.6 ≤ ÉLEVÉ.'""")

# ---------------------------------------------------------------------------------------------

### 4 · Protection-zone risk classification + AI recommendations

# ---------------------------------------------------------------------------------------------

spark.sql(f"""
CREATE OR REPLACE TABLE {GOLD}.zone_risk AS
WITH tx AS (
  SELECT t.zone_id, count_if(r.risk_tier = 'ÉLEVÉ') AS high_risk_transformers, count(*) AS n_transformers
  FROM {GOLD}.transformers t LEFT JOIN {GOLD}.transformer_risk r USING (transformer_id) GROUP BY t.zone_id),
z AS (
  SELECT z.zone_id, z.device_type, z.line_id, z.substation_code, z.ced_code, z.region_name, z.n_customers,
         z.avg_pole_age_years, z.interruptions_3m, z.interruptions_6m, z.chi_3m, z.chi_prev_3m, z.chi_6m,
         z.centroid_lon, z.centroid_lat,
         coalesce(tx.high_risk_transformers, 0) AS high_risk_transformers,
         CASE WHEN z.chi_prev_3m > 0 THEN round(100 * (z.chi_3m - z.chi_prev_3m) / z.chi_prev_3m, 0) END AS chi_trend_pct
  FROM {GOLD}.protection_zones z LEFT JOIN tx USING (zone_id)),
scored AS (
  SELECT *,
    round(0.45 * percent_rank() OVER (ORDER BY chi_6m)
        + 0.20 * percent_rank() OVER (ORDER BY coalesce(chi_trend_pct, 0))
        + 0.20 * percent_rank() OVER (ORDER BY avg_pole_age_years)
        + 0.15 * percent_rank() OVER (ORDER BY high_risk_transformers), 3) AS risk_score
  FROM z)
SELECT *, CASE WHEN risk_score >= 0.75 THEN 'ÉLEVÉ' WHEN risk_score >= 0.5 THEN 'MOYEN' ELSE 'FAIBLE' END AS risk_tier
FROM scored""")

# AI Functions: bilingual recommendation for the top-15 zones (falls back gracefully if the endpoint is unavailable)
try:
    spark.sql(f"""
    CREATE OR REPLACE TABLE {GOLD}.zone_risk_recommendations AS
    SELECT zone_id,
      ai_query('{LLM_ENDPOINT}',
        concat('Tu es ingénieur fiabilité dans une société de distribution d''électricité au Québec. ',
               'Zone de protection ', zone_id, ' (', device_type, ', ligne ', line_id, ', ', region_name, '). ',
               'Clients: ', n_customers, '. Interruptions 6 mois: ', interruptions_6m,
               '. CHI 6 mois: ', chi_6m, '. Tendance CHI 3 mois vs 3 mois précédents: ', coalesce(chi_trend_pct, 0), '%. ',
               'Âge moyen des poteaux: ', avg_pole_age_years, ' ans. Transformateurs à risque élevé de surcharge l''hiver prochain: ',
               high_risk_transformers, '. Donne UNE recommandation opérationnelle concise (max 35 mots) en français, ',
               'puis la même en anglais, séparées par " || ". Pas de préambule.'),
        modelParameters => named_struct('max_tokens', 200, 'temperature', 0.2)) AS recommendation
    FROM {GOLD}.zone_risk ORDER BY risk_score DESC LIMIT 15""")
except Exception as e:  # noqa: BLE001
    print(f"ai_query unavailable, continuing without recommendations: {e}")
    spark.sql(f"CREATE OR REPLACE TABLE {GOLD}.zone_risk_recommendations (zone_id STRING, recommendation STRING)")

spark.sql(f"""COMMENT ON TABLE {GOLD}.zone_risk IS
  'Classification du risque des zones de protection / protection-zone risk: weighted percentile of CHI 6 months (45 %), CHI trend (20 %), average pole age (20 %), predicted high-risk transformers (15 %). risk_tier ÉLEVÉ ≥ 0.75, MOYEN ≥ 0.5.'""")

# ---------------------------------------------------------------------------------------------

### 5 · Operational tables for Lakebase (scalar columns, primary keys, CDF on)

# ---------------------------------------------------------------------------------------------

OPS = {
    "ops_transformer_status": f"""
        SELECT t.transformer_id, t.line_id, t.substation_code, t.ced_code, t.zone_id, t.kva, t.n_customers,
               t.max_overload_pct_hiver_2026 AS max_overload_pct_last_winter,
               t.days_over_150_hiver_2026 AS days_over_150_last_winter,
               round(r.risk_score, 3) AS risk_score_next_winter, r.risk_tier, t.lon, t.lat,
               current_timestamp() AS updated_at
        FROM {GOLD}.transformers t LEFT JOIN {GOLD}.transformer_risk r USING (transformer_id)""",
    "ops_zone_risk": f"""
        SELECT z.zone_id, z.device_type, z.line_id, z.substation_code, z.ced_code, z.n_customers,
               z.interruptions_3m, z.interruptions_6m, z.chi_6m, z.chi_trend_pct, z.avg_pole_age_years,
               z.high_risk_transformers, z.risk_score, z.risk_tier,
               trim(element_at(split(rec.recommendation, '\\\\|\\\\|'), 1)) AS recommendation_fr,
               trim(element_at(split(rec.recommendation, '\\\\|\\\\|'), 2)) AS recommendation_en,
               z.centroid_lon AS lon, z.centroid_lat AS lat, current_timestamp() AS updated_at
        FROM {GOLD}.zone_risk z LEFT JOIN {GOLD}.zone_risk_recommendations rec USING (zone_id)""",
    "ops_active_outages": f"""
        SELECT outage_id, zone_id, device_type, line_id, substation_code, ced_code, start_ts, cause,
               customers_interrupted, duration_h AS elapsed_h, chi AS chi_so_far,
               fault_lon AS lon, fault_lat AS lat, current_timestamp() AS updated_at
        FROM {GOLD}.outages WHERE is_ongoing""",
    "ops_line_status": f"""
        SELECT l.line_id, l.substation_code, l.substation_name, l.ced_code, l.region_name, l.length_km,
               l.n_customers, l.n_transformers,
               coalesce(a.active_outages, 0) AS active_outages, coalesce(a.customers_out, 0) AS customers_out,
               coalesce(r.high_risk_transformers, 0) AS high_risk_transformers,
               coalesce(z.chi_6m, 0) AS chi_6m, current_timestamp() AS updated_at
        FROM {GOLD}.lines l
        LEFT JOIN (SELECT line_id, count(*) AS active_outages, sum(customers_interrupted) AS customers_out
                   FROM {GOLD}.outages WHERE is_ongoing GROUP BY line_id) a USING (line_id)
        LEFT JOIN (SELECT line_id, count_if(risk_tier = 'ÉLEVÉ') AS high_risk_transformers
                   FROM {GOLD}.transformer_risk GROUP BY line_id) r USING (line_id)
        LEFT JOIN (SELECT line_id, sum(chi) AS chi_6m FROM {GOLD}.outages
                   WHERE start_ts >= add_months(current_date(), -6) GROUP BY line_id) z USING (line_id)""",
}
OPS_KEYS = {"ops_transformer_status": "transformer_id", "ops_zone_risk": "zone_id",
            "ops_active_outages": "outage_id", "ops_line_status": "line_id"}

# MERGE (not CREATE OR REPLACE) keeps each table's identity stable, so the Lakebase synced tables
# stay incremental via Change Data Feed instead of breaking their streaming checkpoints.
for table, query in OPS.items():
    key = OPS_KEYS[table]
    spark.sql(f"CREATE TABLE IF NOT EXISTS {GOLD}.{table} TBLPROPERTIES (delta.enableChangeDataFeed = true) AS {query}")
    spark.sql(f"""
        MERGE WITH SCHEMA EVOLUTION INTO {GOLD}.{table} AS t
        USING ({query}) AS s ON t.{key} = s.{key}
        WHEN MATCHED THEN UPDATE SET *
        WHEN NOT MATCHED THEN INSERT *
        WHEN NOT MATCHED BY SOURCE THEN DELETE""")
    print(table, spark.table(f"{GOLD}.{table}").count())
